<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Meeze.ThinIce.Auth\Meeze.ThinIce.Auth.csproj" />
    <ProjectReference Include="..\Meeze.ThinIce.Iceberg\Meeze.ThinIce.Iceberg.csproj" />
    <ProjectReference Include="..\Meeze.ThinIce.Iceberg.LocalDev\Meeze.ThinIce.Iceberg.LocalDev.csproj" />
  </ItemGroup>

</Project>
